PRIV-157201 don't re queue if task is not registered for the particular broker
securitiai/machinery pull request #18
Opened 2024-09-24 07:42 UTC by BilluMeow

If the task is not registered, we dont re queue it.

2024-09-26 10:05 UTC, Uzair614 approved these changes

2024-09-26 22:16 UTC, bharat-p requested changes

2024-09-26 22:16 UTC, bharat-p commented on v1/brokers/redis/goredis-dlq.go
> +		// deleting sig so that this isn't picked up by redis-reaper later
we can still leave the original log in place, so we can identify tasks which are not registered correctly

2024-09-26 22:16 UTC, bharat-p commented on v1/brokers/redis/goredis.go
> +		// can just return nil here, because retries for this broker
same as previous comment, please leave the log in place

2024-09-27 16:41 UTC, bharat-p approved these changes

2024-09-27 16:41 UTC, merged